### ISSUE TITLE
ENH: Update pysatMagVect to OMMBV

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatMissions#19]
**Is your feature request related to a problem? Please describe.**
The spacecraft methods are a mix of types.  Likewise, pysatMagVect functions are scattered throughout.

**Describe the solution you'd like**
Some of the spacecraft functions could be regrouped under pysatMagVect.

**Additional context**
See #9 for further context.

**Comment by rstoneback** [comment]
I was just thinking about this looking at your pull. For completeness of the record, pysatMagVect is now OMMBV.
https://github.com/rstoneback/OMMBV

**Comment by jklenzing** [comment]
Requires pypi access for OMMBV to implement

**Comment by jklenzing** [comment]
Can be implemented now, but must be installed with --no-binary option

**Comment by jklenzing** [comment]
See https://github.com/rstoneback/OMMBV/issues/50

**Comment by jklenzing** [comment]
Closing with merge of #53
