### ISSUE TITLE
ENH: Generalize project_ecef_vector_onto_sc

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysatMissions#29]
**Is your feature request related to a problem? Please describe.**
The code works for projecting any ecef vector onto the s/c but the documentation specifies a particular one.

Further, the labels used to access some variables are hard coded in the method. Allowing users to provide labels makes this a very general function.

**Describe the solution you'd like**
Add more user input labels, and modify docstring.

**Describe alternatives you've considered**
We could leave as is but it is unnecessarily restrictive.

**Additional context**

**Comment by jklenzing** [comment]
If we generalize this, is there any difference from just using the function from pysatMagVect/OMMBV?

**Comment by rstoneback** [comment]
No. Good point. I suppose this is closed then.
