### ISSUE TITLE
TST: End-to-end test of instrument

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatMissions#3]
An end-to-end test of the instrument similar to test_instruments.py in pysat needs to be incorporated.  The code can be adapted and customized from that code, but needs to be made pytest compatible.  Since there is currently one instrument, and it does not rely on downloads, much of the code can be customized for this particular use.  Future instruments in this class would likely use a similar method.

To close:
- [x] Incorporate test_instruments class into testing
- [x] Make pytest-compatible (remove init function in class and restructure)
- [x] Streamline download checks

**Comment by rstoneback** [comment]
It would probably be best if we can just use the test_instruments code that is within pysat. pysat needs to set the standard to ensure compatibility. It is also easier to develop new pysat instruments if there is established test code.

**Comment by jklenzing** [comment]
I think that would simplify things for adding instruments in general, but it will complicate things for instruments that are dependency-heavy, like this one.  Adding to agenda for next meeting.

**Comment by rstoneback** [comment]
Sounds good. I don’t think we have to add sgp4 to pysat, we can likely just import the test_instruments code into sgp4 (perhaps after some work) and have it do its thing on the MissionPlanning side.

**Comment by jklenzing** [comment]
Clearing milestones for now since this is dependent on pysat 3.0.0.

**Comment by jklenzing** [comment]
Closing with merge of #39
