### ISSUE TITLE
BUG: Instrument registration does not work

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatMissions#49]
**Describe the bug**
If I try to register the instruments in pysat, the registry is updated accordingly.  However, pysat will search in the main package for the instruments rather than loading them from the registry.

**To Reproduce**
```
import pysat
import pysatMissions
pysat.utils.registry.register_by_module(pysatMissions.instruments)
sgp4 = pysat.Instrument('pysat', 'sgp4')
```
produces
```
ModuleNotFoundError: No module named 'pysat.instruments.pysat_sgp4'
```
Presumably this is because the platform name is `pysat`.

**Expected behavior**
Should load from pysatMissions.

**Additional context**
This could be solved here by renaming the platform or in the main package by adjusting how the code works.  Tagging @rstoneback.

**Comment by rstoneback** [comment]
The ‘pysat’ platform is reserved for instrument support files within pysat itself. The platform name for pysat_sgp4 will need to be updated to something else.

**Comment by jklenzing** [comment]
Possibilities for a new platform:
- orbprop
- orbital
- propagator

**Comment by jklenzing** [comment]
Closing with merge of #52
