### ISSUE TITLE
TST/BUG: OMMBV requires manual install on GitHub Actions

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatMissions#63]
**Describe the bug**
OMMBV does not install from pip. Some sort of numpy conflict.

**To Reproduce**
See logs here 
https://github.com/pysat/pysatMissions/actions/runs/1099735603

Currently using --no-binary flag to install separately,  likely needs updates at main package.  Documented there at https://github.com/rstoneback/OMMBV/issues/50

**Comment by rstoneback** [comment]
The line that is causing an issue is, 
```
from numpy.distutils.core import setup, Extension
```

I don't see why it is a problem. Checked against apexpy and both packages have the same code.

**Comment by rstoneback** [comment]
apexpy: https://github.com/aburrell/apexpy/blob/main/setup.py
OMMBV: https://github.com/rstoneback/OMMBV/blob/main/setup.py

**Comment by jklenzing** [comment]
Yeah, I've gone through the code as well and don't know why this is an issue.  The only possibility is something to do with the wheels, but I thought we were bypassing those on github actions anyway.

**Comment by rstoneback** [comment]
According to the log it downloaded a .gz for both OMMBV and apexpy. The only difference between the two before the offending line is, 
```
here = os.path.abspath(os.path.dirname(__file__))
version_filename = os.path.join('OMMBV', 'version.txt')
with open(os.path.join(here, version_filename)) as version_file:
    version = version_file.read().strip()
```
but I don't see how that would mess with a numpy install.

**Comment by aburrell** [comment]
I came across issues accessing the `__file__` variable somewhere (either apexpy or aacgmv2).  For whatever reason, it isn't always accessible.  Had to use something else instead.

**Comment by rstoneback** [comment]
Thanks for the tip.

**Comment by jklenzing** [comment]
Adding notes here from discussion at OMMBV: the --no-binary option is not needed, it has to be a separate install command after numpy is already installed.  Working theory is that dependencies are not configured in OMMBV, leading to "numpy not found" error.

**Comment by rstoneback** [comment]
I believe numpy has to be installed before you can install python + fortran combos. I’m not sure it is enough to list numpy as a requirement. This is coming from a memory of some discussion I read years back.

**Comment by jklenzing** [comment]
From the logs:
```
Collecting apexpy
  Downloading apexpy-1.1.0.tar.gz (5.9 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting geospacepy
  Downloading geospacepy-0.2.2.tar.gz (33 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting numpy
  Using cached numpy-1.21.5-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Collecting OMMBV
  Downloading OMMBV-0.5.5.tar.gz (63 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
```
followed by
```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-d3a82i26/ommbv_50394f74215b4d26aaa2fcb3dbd3d282/setup.py", line 17, in <module>
      from numpy.distutils.core import setup, Extension
  ModuleNotFoundError: No module named 'numpy'
```
apexpy works fine.  Looking at the normal logs, it collects all the packages first, them installs them in an order that makes sense.  The failure is occuring during collection.  I think if the metadata is stored in setup.cfg, it will be collected without having to run setup.py before numpy is installed.  At least, this is the only difference I see between OMMBV and apexpy at the moment.  It's a working theory, but I don't have a way to test it at the moment.  The current pull at OMMBV should fix this, but we won't know until it's released.

**Comment by jklenzing** [comment]
Just found this which is similar to what I am thinking: https://stackoverflow.com/questions/11015692/pip-fails-to-install-packages-from-requirements-txt

```
It looks like the numexpr package has an install-time dependency on numpy. Pip makes two passes through your requirements: first it downloads all packages and runs each one's setup.py to get its metadata, and then it installs them all in a second pass.

So, numexpr is trying to import from numpy in its setup.py, but when pip first runs numexpr's setup.py, it has not yet installed numpy.

This is also why you don't see this error when you install the packages one by one: if you install them one at a time, numpy will be fully installed in your environment before you pip install numexpr.
```

**Comment by rstoneback** [comment]
Thanks for looking into this @jklenzing. Sounds like it is release time :)

**Comment by rstoneback** [comment]
OMMBV 1.0 has been released to pypi as well. Hopefully it works!

**Comment by jklenzing** [comment]
Just tried a test branch.  It definitely tries 1.0.0, but still searches setup.py for metadata and has the same error as before.

**Comment by rstoneback** [comment]
That's a bummer.

**Comment by jklenzing** [comment]
Added more notes at rstoneback/OMMBV#50.   It looks like PEP 518 covers this very problem.

**Comment by rstoneback** [comment]
Thanks! I will add it to the list this week. Focus is primarily social media and prep and turns out it is tiring 🐒

**Comment by rstoneback** [comment]
I've incorporated the file from the notes and hopefully v1.0.1 does the trick.
